[package]
name = "bencedit"
version = "0.3.0"
authors = ["Mark Nokalt <marknokalt@live.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
nanoserde = "0.1"

[dependencies.bencode]
git = "https://github.com/manokara/bencode-rs"
rev = "v0.8.1"
features = ["json"]
