[package]
name = "bencedit"
version = "0.1.0"
authors = ["Mark Nokalt <marknokalt@live.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
nanoserde = "0.1"

[dependencies.bencode]
git = "https://github.com/manokara/bencode-rs"
rev = "ca14fb5"
features = ["json"]

